export const DUMMY_TAB = {
    id: -1,
    index: -1,
    windowId: -1,
    active: false,
    pinned: false,
    highlighted: false,
    discarded: false,
    autoDiscardable: false,
    mutedInfo: { muted: false },
    url: ``,
    title: ``,
    favIconUrl: ``,
    status: ``,
    incognito: false,
    width: 0,
    height: 0,
    sessionId: ``,
    selected: false,
    groupId: -1,
} as const satisfies chrome.tabs.Tab;
